[NCM] Fix flaky profile match test (#41497)
### What does this PR do?
https://dd.slack.com/archives/C07S0UH4R0C/p1759346482080039
<img width="998" height="168" alt="image" src="https://github.com/user-attachments/assets/0615a8e5-c358-48e6-b9e9-ee57460baf3b" />
Failing test: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1158167713#L2222
```
    networkconfigmanagement_test.go:349:
        	Error Trace:	/go/src/github.com/DataDog/datadog-agent/pkg/collector/corechecks/networkconfigmanagement/networkconfigmanagement_test.go:349
        	Error:      	Not equal:
        	            	expected: &profile.NCMProfile{BaseProfile:profile.BaseProfile{Name:"p1"}, Commands:map[profile.CommandType][]string{"running":[]string{"show running-config"}, "startup":[]string{"show startup-config"}, "version":[]string{"show version"}}}
        	            	actual  : &profile.NCMProfile{BaseProfile:profile.BaseProfile{Name:"p2"}, Commands:map[profile.CommandType][]string{"running":[]string{"show running-config"}, "startup":[]string{"show startup-config"}, "version":[]string{"show version"}}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  BaseProfile: (profile.BaseProfile) {
        	            	-  Name: (string) (len=2) "p1"
        	            	+  Name: (string) (len=2) "p2"
        	            	  },
        	Test:       	TestCheck_FindMatchingProfile
```
im sorry i repent for my sins of adding flaky test

### Motivation

### Describe how you validated your changes

### Additional Notes

(cherry picked from commit ac7cb13a42fee713a0e57ccd72820b857ac5724e)