name git as a build dependency
The build requires `git`:
```console
root@e558170fe4f1:/mnt/src# invoke agent.build --build-include=apm
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/local/lib/python3.10/dist-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.10/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.10/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/src/tasks/__init__.py", line 8, in <module>
    from . import (
  File "/mnt/src/tasks/pylauncher.py", line 14, in <module>
    PYLAUNCHER_BIN_PATH = os.path.join(get_root(), "bin", "pylauncher")
  File "/mnt/src/tasks/utils.py", line 313, in get_root
    return check_output(['git', 'rev-parse', '--show-toplevel']).decode('utf-8').strip()
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
root@e558170fe4f1:/mnt/src#
```