Fix non-deterministic test in dd_discovery
### What does this PR do?
Fix the `returns_empty_when_fdinfo_not_accessible` test to use a guaranteed non-existent PID instead of `1234`.

### Motivation
The test would fail in CI:
```
failures:
---- procfs::fd::tests::get_log_files::returns_empty_when_fdinfo_not_accessible stdout ----
thread 'procfs::fd::tests::get_log_files::returns_empty_when_fdinfo_not_accessible' (5788) panicked at pkg/discovery/module/rust/src/procfs/fd.rs:461:13:
assertion failed: result.is_empty()
```
([example](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1432568547#L2246))

PID 1234 might exist and be accessible with root permissions in the container used in CI.

### Additional Notes
`i32::MAX` (2,147,483,647) is guaranteed to never be a valid process PID in Linux:
- https://github.com/torvalds/linux/blob/master/include/linux/threads.h#L31
- https://github.com/torvalds/linux/blob/master/kernel/pid.c#L64C26-L64C39

The test should now be more deterministic.