Allow BSP-aware IDEs to sync with `bazel`
IntelliJ IDEA, GoLand and other BSP-aware IDEs can sync with `bazel`
(i.e. fetch its project structure) provided the Build Server Protocol
folder is tracked by the `bazel` server, otherwise one gets sth like:
```
Label '//.bazelbsp/aspects:core.bzl' is invalid because '.bazelbsp/aspects' is not a package; perhaps you meant to put the colon here: '//:.bazelbsp/aspects/core.bzl'?
INFO: Found 66 targets...
ERROR: command succeeded, but not all targets were analyzed
ERROR: Build did NOT complete successfully
FAILED:
INFO: Build Event Protocol files produced successfully.
Command completed in 4.6s (exit code 1)
```

The fix is trivial: remove the offending line from `.bazelignore`:
bazelbuild/intellij#7334.