[CWS] fix TestProcessContext/args-options on ubuntu 25.10 (#42305)
### What does this PR do?

On ubuntu 25.10:
```
$ ls --block-size 123
error: equal sign is needed when assigning values to '--block-size=<BLOCK_SIZE>'

For more information, try '--help'.
```
you need to use `ls --block-size=123`.

`TestProcessContext/args-options` depends on this behavior, so this PR fixes this by using the syscall tester instead, and testing both options passing strategies.

### Motivation

### Describe how you validated your changes

### Additional Notes


Co-authored-by: paul.cacheux <paul.cacheux@datadoghq.com>