[Backport 7.76.x] Replace custom `golangci-lint` build with `depguard` rule
Backport e2fe6b715c360f130da07e4ad7521c5359f30280 from #45521.

 ___

### What does this PR do?
Migrate the custom `pkgconfigusage` plugin for `golangci-lint` to an equivalent `depguard` rule, eliminating the need for rebuilding `golangci-lint` from downloaded sources.

Changes:
- migration of `pkgconfigusage` itself, from a `golangci-lint` plugin (#28382, #39367) to a rule for the depguard (v2) plugin, while preserving its name for traceability,
- move file exclusions to that rule configuration, while removing those that no longer exist or are no longer violating the rule:
  - `comp/aggregator/demultiplexer/demultiplexerimpl/test_agent_demultiplexer.go`,
  - `comp/core/agenttelemetry/impl/config.go`,
  - `comp/core/config/config_mock.go`,
  - `comp/core/workloadfilter/def/utils.go`,
  - `comp/core/workloadmeta/collectors/internal/process/process_collector.go`,
  - `comp/core/workloadmeta/collectors/util/process_util_linux.go`,
  - `comp/dogstatsd/listeners/udp.go`,
  - `comp/remote-config/rcservice/rcserviceimpl/rcservice.go`,
  - `comp/remote-config/rcservicemrf/rcservicemrfimpl/rcservicemrf.go`,
- conversely move locally inhibited `// nolint:pkgconfigusage` to file exclusions:
  - `comp/core/config/params.go`,
  - `comp/core/workloadfilter/baseimpl/filter_utils.go`,
  - `comp/core/workloadfilter/catalog/filter_config.go`,
- ~update `pkgconfigusage_test` to validate the effectiveness of the rule configuration defined in `.golangci.yml`,~
- remove custom `golangci-lint` build infrastructure.

### Motivation
This change kills several birds with one stone:
1. preparation step for the Go build migration to Bazel ([ABLD-317]): while looking for an isolated component with minimal dependencies to introduce the first Go toolchain as part of the ongoing Bazel migration, the custom `golangci-lint` build initially seemed to be a good candidate, but it turns out we can spare time by removing the said build at all,
2. standardization: the `golangci-lint` v2 upgrade (#43501) introduced `depguard` v2 support with file-based import restrictions using `glob` patterns, enabling the same architectural enforcement without a custom plugin,
3. reliability: the custom plugin build process obviously takes time and occasionally failed in CI and locally with:
   ```
   Error: build process: clone golangci-lint: git clone --branch v2.7.0 --single-branch --depth 1 -c advice.detachedHead=false -q https://github.com/golangci/golangci-lint.git: exit status 128
   ```
   ([example CI log](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1369979128#L98))

### Describe how you validated your changes
First commit had `pkgconfigusage_test` validating the actual rule configuration defined in `.golangci.yml` by parsing it and running the `depguard` analyzer based on the existing `analysistest.Run()` tool with `// want` comments in sample files: https://github.com/DataDog/datadog-agent/blob/ed573773ef478707b18ca677cab5d50524bd8c89/pkg/linters/testdata/src/comp/a.go#L9

The second commit removed this test as per [review comments](https://github.com/DataDog/datadog-agent/pull/45521#discussion_r2729639068). It however remains possible to verify the `pkgconfigusage` rule works as expected by simply removing a file from the exclusions and the linter will spot it.

[ABLD-317]: https://datadoghq.atlassian.net/browse/ABLD-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>