[Backport 7.70.x] fix(kafka): Use available bitnami images (#40368)
Backport f2b1fcd48cd96701f791f82fda5ae8ac3672b8c9 from #40355.

___

### What does this PR do?
Use the `bitnami` images from the
[bitnamilegacy](https://hub.docker.com/u/bitnamilegacy) registry.

### Motivation
Agent6 pipeline kmt jobs started to
[fail](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1103480000).
```
Error: GET https://index.docker.io/v2/bitnami/kafka/manifests/3.4: MANIFEST_UNKNOWN: manifest unknown; unknown tag=3.4
```
On the `bitnami` [docker page](https://hub.docker.com/r/bitnami/kafka)
they alert about progressive deprecation of their images from 28AUG25.
IIUC, only the `latest` tag will be available soon
```
Bitnami will begin deprecating support for non-hardened, Debian-based software images in its free tier and will gradually remove tags from the public catalog. As a result, community users will have access to a reduced number of hardened images. These images are published only under the “latest” tag and are intended for development purposes
```
As we want to keep using the same version we move to their copy on the
[bitnamilegacy](https://hub.docker.com/u/bitnamilegacy) registry

### Describe how you validated your changes (if not by through tests)
CI should be green

### Possible Drawbacks / Trade-offs

Co-authored-by: Nicolas Schweitzer <nicolas.schweitzer@datadoghq.com>
Co-authored-by: guyarb <guy20495@gmail.com>