[WP] Fix filtersToProgs with wrong instructions cap (#51499)
### What does this PR do?
Fix the function `filtersToProgs`.

### Motivation
The function was intended to generate programs capped at 4,000 instructions. However, the algorithm would split the program only after adding the filter that caused the instruction limit to be exceeded.

### Describe how you validated your changes
Here is an example of the sizes of the progs before and after the fix.

```
=== RUN   TestRawPacketFilter/all-with-limit
len(prog.Instructions): 7142
len(prog.Instructions): 7126
len(prog.Instructions): 7146
len(prog.Instructions): 7102
len(prog.Instructions): 7138
len(prog.Instructions): 3555

```

After the fix the test fails because we need more than 5 tail calls.

```
=== RUN   TestRawPacketFilter/all-with-limit
    network_test.go:799:
        	Error Trace:	/Users/theo.putegnat/dd/datadog-agent/pkg/security/tests/network_test.go:799
        	            				/Users/theo.putegnat/dd/datadog-agent/pkg/security/tests/network_test.go:841
        	Error:      	Received unexpected error:
        	            	1 error occurred:
        	            		* maximum allowed tail calls reach: 5 vs 5

        	Test:       	TestRawPacketFilter/all-with-limit
len(prog.Instructions): 3591
len(prog.Instructions): 3577
len(prog.Instructions): 3562
len(prog.Instructions): 3590
len(prog.Instructions): 3572
len(prog.Instructions): 3596

```

For example, the first filter contains 87 instructions (3,500 NOPs), including all the additional instructions. After the fix, the instruction count increases by 4 due to the insertion of the tail call.

Co-authored-by: theo.putegnat <theo.putegnat@datadoghq.com>