update test that was flakey on windows (#42005)
### What does this PR do?
Fixes flakey deployment test on windows

### Motivation
```
=== Failed
=== FAIL: pkg/collector/corechecks/cluster/ksm/customresources TestDeploymentRolloutGeneration_OngoingRollout (0.00s)
    deployment_test.go:101:
        	Error Trace:	C:/buildroot/datadog-agent/pkg/collector/corechecks/cluster/ksm/customresources/deployment_test.go:101
        	Error:      	"0" is not greater than "0"
        	Test:       	TestDeploymentRolloutGeneration_OngoingRollout
        	Messages:   	Rollout duration should be greater than 0 for ongoing rollout
=== FAIL: pkg/collector/corechecks/cluster/ksm/customresources TestDeploymentRolloutGeneration_OngoingRollout (re-run 1) (0.00s)
    deployment_test.go:101:
        	Error Trace:	C:/buildroot/datadog-agent/pkg/collector/corechecks/cluster/ksm/customresources/deployment_test.go:101
        	Error:      	"0" is not greater than "0"
        	Test:       	TestDeploymentRolloutGeneration_OngoingRollout
        	Messages:   	Rollout duration should be greater than 0 for ongoing rollout
=== FAIL: pkg/collector/corechecks/cluster/ksm/customresources TestDeploymentRolloutGeneration_OngoingRollout (re-run 2) (0.00s)
    deployment_test.go:101:
        	Error Trace:	C:/buildroot/datadog-agent/pkg/collector/corechecks/cluster/ksm/customresources/deployment_test.go:101
        	Error:      	"0" is not greater than "0"
        	Test:       	TestDeploymentRolloutGeneration_OngoingRollout
        	Messages:   	Rollout duration should be greater than 0 for ongoing rollout
```
### Describe how you validated your changes

### Additional Notes

(cherry picked from commit 8310fe095eef663f8eb0455d05a02ba60e8cfeba)