Bump `gcc-toolchain` for `bazel mod deps` compat
Now f0rmiga/gcc-toolchain#211 got merged, we can remove the
corresponding patch we had to put in place for `bazel mod deps`
compatibility.

For the record, the error was:
```sh
$ bazel mod deps
ERROR: [redacted]/gcc_toolchain+/internal.bzl:43:17: Traceback (most recent call last):
        File "[redacted]/gcc_toolchain+/internal.bzl", line 117, column 9, in _non_bazel_dependencies_ext_impl
                _avl()
        File "[redacted]/gcc_toolchain+/internal.bzl", line 43, column 17, in _avl
                http_archive(
Error in repository_rule: no repository visible as '@' in the extension '@@gcc_toolchain+//:internal.bzl%non_bazel_dependencies', but referenced by label '@//:examples/avl/avl.BUILD.bazel' in attribute 'build_file' of http_archive 'avl'.
ERROR: error evaluating module extension @@gcc_toolchain+//:internal.bzl%non_bazel_dependencies
```