[ABLD-317] Add initial Go toolchain for Bazel with `modparser` as 1st module
### What does this PR do?

tl;dr: apply recommended setup from [Go with Bzlmod](https://github.com/bazel-contrib/rules_go/blob/master/docs/go/core/bzlmod.md).

`modparser` is now built, tested and executed through `bazel`.

### Motivation
[ABLD-317](https://datadoghq.atlassian.net/browse/ABLD-317).

`modparser` happens to be a good candidate to start with: tiny binary, few dependencies, few changes over time. Prior to this PR, its tests were not run in CI and had to be fixed (#45721).

### Additional Notes
`.adms/bazel/adms.mirror.cfg`: new `rewrite` rule to download the Go SDK [due to](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1409573778#L3010):
```
ERROR: no such package '@@rules_go++go_sdk+main___download_0//': java.io.IOException: Cache miss and no url specified - Configured URL rewriter blocked all URLs: [https://dl.google.com/go/go1.25.6.linux-amd64.tar.gz] - This blocking should only be happening in CI - reach out to Datadog#dependency-management
```

`.gitlab/build/bazel/lint.yml`: Go linting jobs to make sure we remain in-sync.

`.gitlab/build/bazel/tests.yml`: extend the scope of `bazel test` (only on Linux/x86_64 only for the time being) to catch `modparser` tests as well as any newly migrated Go module.

`internal/tools/modparser/BUILD.bazel`: **generated** by `gazelle`.

`tasks/libs/common/gomodules.py`: now runs `modparser` through `bazel run`.

`BUILD.bazel`: plugs `gazelle` into the build, with a TODO list of excluded directories containing `go.mod` files. Removing a `# gazelle:exclude DIR` line will lead `bazel run //:gazelle` to generate `BUILD.bazel` files for each `go.mod` file under `DIR`.

`MODULE.bazel`: the Go SDK version is **read** from the root `go.mod` file, and the list of Go repositories is **generated** by `bazel run //:gazelle`.