`new-e2e-containers-eks`: avoid `exec`'ing on evicted pods
This fixes a race condition in `TestEKSSuite/TestVersion` where the test
would randomly fail with:
> unable to upgrade connection: container not found

The test was using `Limit: 1` to select a single pod, which would return
an arbitrary pod from the list.
During an eviction, this could select a pod that was being terminated,
causing the connection to fail.

From the failing job logs
(https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1275146058):
```
Error:          	Received unexpected error:
                	command terminated with exit code 126
                	unable to upgrade connection: container not found ("cluster-agent")
```

Post-failure diagnostics showed 2 cluster-agent pods were running after
the test, suggesting that it would have been possible to `exec` on one
of them.

Proposed solution:
- replace `Limit: 1` to get all candidate pods,
- filter out pods being evicted (scheduled for deletion),
- filter out containers that are not `Ready` yet.