Revert "pkg/trace: use go.uber.com/atomic (#12120)" (#12568)
* Revert "pkg/trace: use go.uber.com/atomic (#12120)"

This reverts commit 2469fbac5d39d3cea002dbf119035b3d48142a17.

This is due serialization issues caused by this change.
Error message from `agent status`:
```
template: /trace-agent.tmpl:46:139: executing "/trace-agent.tmpl" at <.trace_writer.Bytes>: wrong type for value; expected float64; got map[string]interface {}
```

* Revert "pkg/trace: use go.uber.com/atomic (#12120)"

This reverts commit 2469fbac5d39d3cea002dbf119035b3d48142a17.

This is due to serialization issues resulting from PR #12120 which block the agent release.
Error message from `agent status` before revert:
```
template: /trace-agent.tmpl:46:139: executing "/trace-agent.tmpl" at <.trace_writer.Bytes>: wrong type for value; expected float64; got map[string]interface {}
```

Below is the revert steps to call out merge conflicts:
```
~ git revert 2469fbac5d39d3cea002dbf119035b3d48142a17
Auto-merging pkg/trace/agent/agent.go
Auto-merging pkg/trace/agent/agent_test.go
Auto-merging pkg/trace/api/responses.go
Auto-merging pkg/trace/go.mod
CONFLICT (content): Merge conflict in pkg/trace/go.mod
Auto-merging pkg/trace/sampler/dynamic_config.go
CONFLICT (content): Merge conflict in pkg/trace/sampler/dynamic_config.go
Auto-merging pkg/trace/sampler/prioritysampler_test.go
CONFLICT (content): Merge conflict in pkg/trace/sampler/prioritysampler_test.go
Auto-merging pkg/trace/sampler/rare_sampler.go
CONFLICT (content): Merge conflict in pkg/trace/sampler/rare_sampler.go
Auto-merging pkg/trace/sampler/remote_rates.go
CONFLICT (content): Merge conflict in pkg/trace/sampler/remote_rates.go
Auto-merging pkg/trace/sampler/remote_rates_test.go
CONFLICT (content): Merge conflict in pkg/trace/sampler/remote_rates_test.go
error: could not revert 2469fbac5... pkg/trace: use go.uber.com/atomic (#12120)
```