Add Battery Check for Mac (#44371)
### What does this PR do?
Original PR (https://github.com/DataDog/datadog-agent/pull/43986) for adding the battery check was reverted (https://github.com/DataDog/datadog-agent/pull/44359) due to #incident-47253. The error was:
```2025-12-17T16:18:24.181035Z 01O Error:
2025-12-17T16:18:24.181036Z 01O 
2025-12-17T16:18:24.181036Z 01O     # github.com/DataDog/datadog-agent/pkg/collector/corechecks/system/battery
2025-12-17T16:18:24.181037Z 01O battery_darwin.m:12:61: error: 'kIOMainPortDefault' is only available on macOS 12.0 or newer [-Werror,-Wunguarded-availability-new]
2025-12-17T16:18:24.181057Z 01O /Applications/Xcode-16.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:112:19: note: 'kIOMainPortDefault' has been marked as being introduced in macOS 12.0 here, but the deployment target is macOS 11.0.0
```

This PR includes the fix that caused the incident.
- kIOMainPortDefault was introduced in macOS 12.0, use kIOMasterPortDefault for older versions

### Motivation
https://datadoghq.atlassian.net/browse/WINA-2068

### Describe how you validated your changes
Ran full pipeline with the fix: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/87391310/

### Additional Notes


Co-authored-by: mrafi97 <mohammad.rafi@datadoghq.com>
Co-authored-by: brian.tu <brian.tu@datadoghq.com>