[AGENTCFG-586] Reduce test flakiness in TestSendToRetryLogic/success_on_second_attempt_after_500_error (#45822)
### What does this PR do?

We saw an e2e test failure due to a late retry:

> Failed
=== RUN   TestSendToRetryLogic/success_on_second_attempt_after_500_error
    send_flare_test.go:409: 
        	Error Trace:	github.com/DataDog/datadog-agent/comp/core/flare/helpers/send_flare_test.go:409
        	Error:      	Should be true
        	Test:       	TestSendToRetryLogic/success_on_second_attempt_after_500_error
        	Messages:   	Retry delay 1 was 1.36471647s, expected around 1s
--- FAIL: TestSendToRetryLogic/success_on_second_attempt_after_500_error (1.38s)

### Motivation

### Describe how you validated your changes

### Additional Notes


Co-authored-by: rahul.kaukuntla <rahul.kaukuntla@datadoghq.com>