tasks: gotest: don't fail when modified packages have no test targets (#57809)
<!--Please give us some feedback on your experience writing this PR ! https://app.datadoghq.com/forms/43db4c02-6837-400c-8083-692e141b1b88 !-->

### What does this PR do?

Fix a false negative when running `dda inv test --only-modified-packages`

### Motivation

This is preventing `git push` when the local changes don't have a test target for the current architecture.

### Describe how you validated your changes

Needed to be able to push the commit from https://github.com/DataDog/datadog-agent/pull/57808.
While attempting to push on linux, since the code is windows only, there are no tests to be run but the task failed with:
```
❯ dda inv test --only-modified-packages
Running tests for the following modules:
- .: ['./comp/etw/impl']
- pkg/util/winutil: ['./etw']
bazel test --config=dd-agent-go-tests-only --build_tests_only //comp/etw/impl:all //pkg/util/winutil/etw:all
INFO: Invocation ID: b0eb3b0a-4873-47ce-95c6-2ccebb2ea3c0
INFO: Checking for file changes...
INFO: Found 0 test targets...
INFO: Elapsed time: 2.533s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
ERROR: No test targets were found, yet testing was requested
```

### Additional Notes


Co-authored-by: hugo.beauzee <hugo.beauzee@datadoghq.com>