regression_detector pr-commenter: omit --for-repo
The `pr-commenter` error message shown in CI seems to indicate that
the `--for-repo` flag is invalid (error message was `pr-commenter:
error: unrecognized arguments: --for-repo=datadog-agent`) so this
commit removes that flag.

Signed-off-by: Geoffrey M. Oxberry <geoffrey.oxberry@datadoghq.com>