Detect connection issue when using FQDN in `diagnose` (#43634)
### What does this PR do?

This PR adds the ability to detect failing connectivity when using an FQDN intake address (ie: `datadoghq.com.`, with the trailing dot) for the `agent diagnose` commands.
When a connection with a FQDN fails, it attempts to connect using a PQDN (without the trailing dot); if it succeeds, it adds remediation information to the diagnostic message.

```
Connection to `https://app.datadoghq.com./api/v1/series` failed
Could not get a response from the endpoint : cannot send the HTTP request to 'https://app.datadoghq.com./api/v1/series' : Post "https://app.datadoghq.com./api/v1/series": stream error: stream ID 1; INTERNAL_ERROR; received from peer
Remediation: The connection with a FQDN failed but is possible with PQDN, please check firewall and/or proxy configuration
Error: cannot send the HTTP request to 'https://app.datadoghq.com./api/v1/series' : Post "https://app.datadoghq.com./api/v1/series": stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

### Motivation

Inform users having Agent connection issues because of FQDN endpoints are not correctly whitelisted in their firewall/proxy.

### Describe how you validated your changes

Validated with a proxy in a custom environment that blocks endpoint addresses using an FQDN.

### Additional Notes


Co-authored-by: fabrice.buoro <fabrice.buoro@datadoghq.com>