Alleviate temporary file conflicts in JUnit uploads
This is to alleviate issues caused by a tool that likely reuses
temporary paths across invocations by assigning each subprocess a
dedicated temporary directory via `TEMP`, `TMP`, and `TMPDIR`
environment variables.

Using `tempfile.TemporaryDirectory` ensures _sufficient entropy_ in the
paths and automatic cleanup, avoiding collisions during concurrent JUnit
uploads.

This change also renames the JUnit tarball using `CI_JOB_NAME_SLUG`
in lieu of `CI_JOB_NAME`, ensuring compatibility with GitLab's
`parallel` feature when experimenting with concurrent test job runs, in
which case `CI_JOB_NAME` includes annoying spaces and, more importantly,
filesystem-incompatible slashes, which result in invalid paths:
- `c:\mnt\junit-tests_windows-x64 3/10.tgz: No such file or directory`
  because `c:\mnt\junit-tests_windows-x64 3` is then expected to be an
  existing _directory_ where to find the `10.tgz` archive,
- `c:\mnt\junit-tests-windows-x64-3-10.tgz` works.
  (`-3-10` is of course absent when not leveraging `parallel`)

While this **does not address deeper concurrency issues** (shared access
to `git` metadata), it isolates usage of temporaries and reduces the
risk of interference between parallel executions leading to errors like:
```
Error: EPERM: operation not permitted, lstat '\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\pkg-UKhsg3\f6db2f7790c415a4726371e606fb3a9b4677c1226d9dfb63fd4798b687ee1579'
    at lstatSync (node:fs:1574:3)
    at rimrafSync (node:internal/fs/rimraf:180:13)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at fixWinEPERMSync (node:internal/fs/rimraf:304:5)
    at rimrafSync (node:internal/fs/rimraf:200:14)
    at Object.rmSync (node:fs:1274:10)
    at removeTemporaryFolderAndContent (pkg/prelude/bootstrap.js:704:10)
    at process.<anonymous> (pkg/prelude/bootstrap.js:711:5) {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: '\\\\?\\C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pkg-UKhsg3\\f6db2f7790c415a4726371e606fb3a9b4677c1226d9dfb63fd4798b687ee1579'
}
```