privileged logs: Included resolved path in error message
Consistently add the resolved path to the error messages from the
system-probe module.  For example, if the configured log file
"dummy.log" is symlinked to "dummy", the currenty error message in the
agent status is:

 Error: failed to open file with system-probe: file descriptor transfer
 failed: failed to open file /dummy.log: non-log file not allowed,
 original error: open /dummy.log: permission denied

This has two issues:
 (1) It's not obvious why dummy.log is a non-log file
 (2) The error refers to "file descriptor transfer failed" which is
     confusing (fdtransfer was the working name for this system-probe
     module)

After this PR:

 Error: failed to open file with system-probe: module error: non-log
 file not allowed: /dummy, original error: open /dummy.log: permission
 denied