[incident-40404] Verify `notarytool`'s resulting status
First, The fallback expression `|| EXIT_CODE=$?` was evaluated in a
subshell, which caused it to be swallowed from the perspective of the
parent shell. The fix simply consists in moving it to the parent shell.

In addition, it turns out that `notarytool submit [...] --wait` doesn't
return a `nonzero` exit code on `Invalid` statuses, which might be by
design (or might be fixed in a later `Xcode` version).

The present change therefore changes the approach to fail fast(er) by
first enabling [recommended shell
flags](https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail),
and then verifying `notarytool log`'s resulting status which should be
exactly `Accepted` as per
https://keith.github.io/xcode-man-pages/notarytool.1.html#wait.

For instance, should `notarytool log`'s resulting status be `Invalid`,
the `agent_dmg-x64-a7` job would then terminate as follows:
```
+ '[' Invalid = Accepted ']'
Attempt #3 failed with error code 1
Running after_script
Cleaning up project directory and file based variables
ERROR: Job failed: exit status 1
```
Conversely, for an `Accepted` resulting status:
```
+ '[' Accepted = Accepted ']'
+ exit 0
\e[0K
Built signed package
$ $S3_CP_CMD $OMNIBUS_PACKAGE_DIR/version-manifest.json $S3_SBOM_STORAGE_URI/$CI_JOB_NAME/version-manifest.json
upload: omnibus/pkg/version-manifest.json to s3://sbom-root-us1-ddbuild-io/datadog-agent/99999999/agent_dmg-x64-a7/version-manifest.json
Running after_script
Saving cache for successful job
Uploading artifacts for successful job
Cleaning up project directory and file based variables
Job succeeded
```