CO-RE: TCPQueueLength and OOM Kill tests are missing some BTF
  [4.14.275-207.503.amzn2.aarch64] started CO-RE
       [4.14.275-207.503.amzn2.aarch64] [pkg/collector/corechecks/ebpf/probe]·✖·✖
       [4.14.275-207.503.amzn2.aarch64] === Failed
       [4.14.275-207.503.amzn2.aarch64] === FAIL: pkg/collector/corechecks/ebpf/probe TestOOMKillProbe (0.17s)
       [4.14.275-207.503.amzn2.aarch64] oom_kill_test.go:88: error loading CO-RE oom-kill probe: could not find BTF data on host. set system_probe_config.allow_runtime_compiled_fallback to true to allow fallback to runtime compilation
       [4.14.275-207.503.amzn2.aarch64]
       [4.14.275-207.503.amzn2.aarch64] === FAIL: pkg/collector/corechecks/ebpf/probe TestTCPQueueLengthTracer (0.17s)
       [4.14.275-207.503.amzn2.aarch64] tcp_queue_length_test.go:71: error loading CO-RE tcp-queue-length probe: could not find BTF data on host. set system_probe_config.allow_runtime_compiled_fallback to true to allow fallback to runtime compilation
       [4.14.275-207.503.amzn2.aarch64]
       [4.14.275-207.503.amzn2.aarch64] DONE 4 tests, 2 failures in 0.367s