Tentatively fix flakiness in `new-e2e-sbom` job
### What does this PR do?
This aims at decreasing intermittent failures of
`TestSBOMKindSuite/TestSBOM` when testing overlayfs scan mode by
ensuring agent pods are fully restarted and stable before verifying SBOM
tags.

### Motivation
The test has been failing intermittently with:
```
Error Trace:    test/new-e2e/tests/sbom/k8s_test.go:354
Error:          unexpected tags: scan_method:filesystem
            	missing tags: ^scan_method:overlayfs$
```
([example](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1388230450))

This might be due to a race condition during agent re-configuration:
when `UpdateEnv` changes the Helm configuration, Kubernetes restarts
agent pods, but the test immediately checks for SBOMs without waiting
for agents to be ready with the new configuration.

### Describe how you validated your changes
Added `testUpAndRunning(1 * time.Minute)` after `UpdateEnv` to wait for
agent pods to be ready and stable before checking SBOMs.

1 minute is sufficient for reconfiguration (not a cold start), and is
consistent with `TestZZUpAndRunning`.

### Additional Notes
The change also addresses TODOs about replacing `!assert.NotEmptyf` by
`require.NotEmptyf` and removes an iteration over a single-element slice
(`[]*corev1.PodList{linuxPods}`).