Remove previous fleet extension if one exists while installing (#50123)
### What does this PR do?
Resolves TODO comment to remove previous extension if it exists in the install process. The remove is implemented right before the new extension directory is moved so that the existing extension won't be removed in a failed install process.

When replacing an existing extension, `installSingle` now backs up the existing extension, runs `removeSingle`, install the new version, and restores the backup on failure. The backup restore process executes the preInstall hooks, copies the backup files back to the extension path, and then executes the postInstall hooks.

### Motivation
`os.Rename` returns EEXIST if the destination directory already exists, which occurs when a DDOT BYOC image is being installed with an existing DDOT installation:
```
$ sudo datadog-agent otel install --registry <custom-registry>
Error: run failed: could not install extensions: extension ddot: could not move ddot to final location: rename /opt/datadog-packages/datadog-agent-extension-2272451981 /opt/datadog-agent/ext/ddot: file exists                                                          
exit status 255                                                                                
```

### Describe how you validated your changes
Unit tests

### Additional Notes


Co-authored-by: stanley.liu <stanley.liu@datadoghq.com>