Update and prevent `MODULE.bazel.lock` file from diverging again (#40394)
### What does this PR do?
1. Run a quick `bazel` command that fails if the `MODULE.bazel.lock` file gets out-of-sync with actually used dependencies,
2. Update `MODULE.bazel.lock` thanks to `bazel mod deps` as advised in the [error message](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1241267622#L40):
```sh
ERROR: The module extension '@@gcc_toolchain+//:internal.bzl%non_bazel_dependencies' does not exist in the lockfile
ERROR: The module extension '@@rules_fuzzing+//fuzzing/private:extensions.bzl%non_module_dependencies' does not exist in the lockfile
ERROR: The module extension '@@pybind11_bazel+//:python_configure.bzl%extension' does not exist in the lockfile
<root> (@_)
ERROR: Results may be incomplete as 3 extensions failed.
Running after script...
$ if [ $CI_JOB_STATUS = failed ]; then
💡 bazel mod deps
```
### Motivation
Faced differences unrelated to my change when invoking `bazel build //...` locally.
### Additional Notes
Currently, there's a problem with the `gcc_toolchain` repo:
```sh
$ bazel mod deps
ERROR: [redacted]/gcc_toolchain+/internal.bzl:43:17: Traceback (most recent call last):
	File "[redacted]/gcc_toolchain+/internal.bzl", line 117, column 9, in _non_bazel_dependencies_ext_impl
		_avl()
	File "[redacted]/gcc_toolchain+/internal.bzl", line 43, column 17, in _avl
		http_archive(
Error in repository_rule: no repository visible as '@' in the extension '@@gcc_toolchain+//:internal.bzl%non_bazel_dependencies', but referenced by label '@//:examples/avl/avl.BUILD.bazel' in attribute 'build_file' of http_archive 'avl'.
ERROR: error evaluating module extension @@gcc_toolchain+//:internal.bzl%non_bazel_dependencies
```
Hence the additional patch, pending:
- f0rmiga/gcc-toolchain#211

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>