discovery: Fix cleanup race in test
Fix this kind of error which happens since we don't wait for the process
holding the port to exit.

 PASS pkg/collector/corechecks/servicediscovery/module.TestServicesBasic (0.02s)
 === RUN   TestServicesPorts
     impl_linux_test.go:143:
         	Error Trace:	impl_linux_test.go:143
         	            	impl_services_test.go:136
         	            	impl_services_test.go:151
         	Error:      	Received unexpected error:
         	            	listen udp4 :8083: bind: address already in use
         	Test:       	TestServicesPorts
 --- FAIL: TestServicesPorts (0.00s)