Move aux `bazel` jobs back to ephemeral runners
It turns out jobs running on persistent runners have to be allow-listed **outside** of the repo:
https://github.com/DataDog/dd-source/blob/e9ab3086d80dcc670af2ebb7d36395d384b5ca60/domains/devex/ci/gitlab/config/k8s/gitlab-runner-k8s-persistent/values/datadog-agent-amd64.yaml#L40-L48

Problems:
- adding a _new_ job would fail on:
  ```
  ERROR: Job failed (system failure): Job is not allowed to run on this runner. For support, please reach out in #ci-infra-support.
  ```
  ([tentative](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1400699592))
- the same would happen when simply _renaming_ an existing job,
- to move forward, a distinct PR would have to be filed to
  https://github.com/DataDog/dd-source and waited for: reviewed,
  approved, merged and eventually in effect (deployed/active)
  ... in addition to the present repo's own Lead Time for Changes...
- the persistent runners seem to be reserved for _occasional_ needs that
  CI does not meet:
  > These were meant to be an experiment
- as per security guidelines, "production" jobs are not allowed to run
  on persistent runners:
  > By production [they mean] "user facing". They are running on default
  > branch and actual developer feature branches.

With this change, we retain the ability to _experiment_ by swapping the
`extends` and `tags` fields.