add a patch to fix .S file compilation & reorganize gcc-toolchain patches (#42674)
### What does this PR do?

Add a new patch allowing to compile `.S` files

### Motivation

ASM with C preprocessor is used in our dependencies and we need to be able to build them.
Without this patch (which only adds `-nostdinc` to the compilation line) the build fails with this kind of error:
```
ERROR: /home/hugo.beauzee/.cache/bazel/_bazel_hugo.beauzee/95605d1a73395e0c041bb302da387b0e/external/+_repo_rules+python3/BUILD.bazel:323:10: Compiling Python/asm_trampoline.S failed: absolute path inclusion(s) found in rule '@@+_repo_rules+python3//:freeze_module':
the source file 'Python/asm_trampoline.S' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
  '/home/hugo.beauzee/.cache/bazel/_bazel_hugo.beauzee/95605d1a73395e0c041bb302da387b0e/external/gcc_toolchain++gcc_toolchains+gcc_toolchain_x86_64/x86_64-unknown-linux-gnu/sysroot/usr/include/stdc-predef.h'
```
bazel will take care of providing all required include flags, but using the built in ones will cause bazel to refuse to build as shown in the error above.

### Describe how you validated your changes

Local builds & CI for `gcrypt` & `zstd` which both include `.S` files

### Additional Notes


Co-authored-by: hugo.beauzee <hugo.beauzee@datadoghq.com>