Enable `bazel --remote_local_fallback` (#43582)
### Motivation
`bazel` started exiting on exit code `39`:
> Blobs required by Bazel are evicted from Remote Cache.


This is caused by (hopefully) transient:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Shard 2: connection error: desc = "transport: Error while dialing: dial tcp: lookup buildbarn-storage-2.buildbarn-storage.buildbarn.local-cluster.local-dc.fabric.dog on 169.254.20.10:53: no such host"
```

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>