bazel: foreign_cc_shared_wrapper: don't provide exports.
When using foreign_cc_shared_wrapper on the same input but to extract 2
different libraries, we end up with the same label being exported twice
which causes some rather obscure build error down the line:
ERROR: /home/hugo.beauzee/.cache/bazel/_bazel_hugo.beauzee/95605d1a73395e0c041bb302da387b0e/external/+_repo_rules+curl/BUILD.bazel:222:18: in cc_shared_library rule @@+_repo_rules+curl//:curl:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 654, column 60, in _cc_shared_library_impl
	File "/virtual_builtins_bzl/common/cc/cc_shared_library.bzl", line 251, column 33, in _build_exports_map_from_only_dynamic_deps
Error: unsupported binary operation: string + Label