Use available `bazel` spawn strategy on Windows
The `sandboxed` spawn strategy is alas unavailable on Windows as of `bazel` 8.3.1:
```
ERROR: 'sandboxed' was requested for mnemonic  but no strategy with that
 identifier was registered. Valid values are: [dynamic_worker,
 standalone, dynamic, remote, worker, local]
```

The present change therefore consists in splitting spawn strategies per OS:
- Darwin & Linux: `sandboxed`, (as earlier)
- Windows: `standalone`. (closest match, that is without involving remote
  execution)

Despite not being isolated, `standalone` is slightly closer to
`sandboxed` than `local` in that it respects _some_ `bazel` restrictions.
(working directory, for instance)