Fix `fetch_secret.sh` to consider command exit codes (#46245)
### What does this PR do?
Make the `fetch_secret.sh` script check the exit code of the command it executes before checking the standard output of that command.

### Motivation
Previously, the script would succeed if the command had printed any character to its standard output (even a single whitespace) - also when the command had terminated with a non-zero exit code.
This caused CI pipelines to continue despite secret fetching failures:
```sh
$ DD_API_KEY="$("$CI_PROJECT_DIR"/tools/ci/fetch_secret.sh "$AGENT_API_KEY_ORG2" token)" || exit $?; export DD_API_KEY
error: reading Vault secret: creating vault client and CI Identity: getting CI Identity token: response status code (500 Internal Server Error) indicates an error
body: GitLab ID token CI identity resolver not initialized
# [... retries...]
error: reading Vault secret: creating vault client and CI Identity: getting CI Identity token: response status code (500 Internal Server Error) indicates an error
body: GitLab ID token CI identity resolver not initialized
# all retries exhausted: should have failed here but:
# `|| exit $?` didn't trigger because `fetch_secret.sh` terminated with exit code `0`
$ DD_APP_KEY="$("$CI_PROJECT_DIR"/tools/ci/fetch_secret.sh "$AGENT_APP_KEY_ORG2" token)" || exit $?; export DD_APP_KEY
```

### Additional Notes
When a command fails, its standard output is unlikely to convey any actionable result.
For instance, flushing standard streams at exit might produce EOL/EOS/EOT characters (`\0`, `\n`) or indentation characters (` `, `\t`).

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>