Revert "[CONS-8547] Fix the logs’ `service` when it comes from `kubernetesResourcesAnnotationsAsTags`" (#57144)
Reverts DataDog/datadog-agent#56519

Speculative: This may be the cause of new failures on main. E.g.
https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/2092123441
```
    suite.go:417: 29-09-2026 22:28:59 - TestKindSuite/TestContainerLifecycleEvents - No change in provisioners, skipping environment update
    suite.go:282: 
        	Error Trace:	test/new-e2e/tests/containers/k8s_test.go:1904
        	            				test/e2e-framework/testing/e2e/suite.go:288
        	            				src/runtime/asm_amd64.s:1771
        	Error:      	Should be true
        	Messages:   	Pod lifecycle event for pod workload-nginx/nginx-5fd9ffbb77-fkh47 does not carry the expected dd_tags: unexpected tags: service:nginx-from-annotation
```