fix(check_for_changes): Use error code rather than stdout (#40104)
<!--
* Contributors are encouraged to read our
[CONTRIBUTING](/CONTRIBUTING.md) documentation.
* Both Contributor and Reviewer Checklists are available at
https://datadoghq.dev/datadog-agent/guidelines/contributing/#pull-requests.
* The pull request:
  * Should only fix one issue or add one feature at a time.
  * Must update the test suite for the relevant functionality.
  * Should pass all status checks before being reviewed or merged.
* Commit titles should be prefixed with general area of pull request's
change.
* Please fill the below sections if possible with relevant information
or links.
-->
### What does this PR do?
Use an error_code in the `check-for-changes` method instead of stdout

### Motivation
In the Github workflow we are running a command which print to stdout,
stored in env var and transferred to Github stack.
```
echo "CHANGES=$(dda inv -- -e release.check-for-changes -r "$MATRIX" "$WARNING")" >> $GITHUB_OUTPUT
```
Since the `dda` migration the stdout output causes [unexpected
errors](https://github.com/DataDog/datadog-agent/actions/runs/17120882608/job/48561289796).
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'integrations-core has a new tag 7.70.0-rc.6 since last release candidate (was 7.70.0-rc.5)'
```
I decided to used an error code to have a more robust transfer of the
env var to Github.
 

### Describe how you validated your changes
Updated the unit test.

I should try to run the command from my branch as well
<!--
Validate your changes before merge, ensuring that:
* Your PR is tested by static / unit / integrations / e2e tests
* Your PR description details which e2e tests cover your changes, if any
* The PR description contains details of how you validated your changes.
If you validated changes manually and not through automated tests, add
context on why automated tests did not fit your changes validation.

If you want additional validation by a second person, you can ask
reviewers to do it. Describe how to set up an environment for manual
tests in the PR description. Manual validation is expected to happen on
every commit before merge.

Any manual validation step should then map to an automated test. Manual
validation should not substitute automation, minus exceptions not
supported by test tooling yet.
-->

### Possible Drawbacks / Trade-offs

### Additional Notes
<!--
* Anything else we should know when reviewing?
* Include benchmarking information here whenever possible.
* Include info about alternatives that were considered and why the
proposed
  version was chosen.
-->