[ABLD-317] Add initial Go toolchain for Bazel with `modparser` as 1st module (#45714)
### What does this PR do?
tl;dr: apply recommended setup from [Go with Bzlmod](https://github.com/bazel-contrib/rules_go/blob/master/docs/go/core/bzlmod.md).

`modparser` is now built, tested and executed through `bazel`.

### Motivation
[ABLD-317: Start bringing in Go toolchains](https://datadoghq.atlassian.net/browse/ABLD-317).

`modparser` happens to be a good candidate to start with: tiny binary, few dependencies, few changes over time. Prior to this PR, its tests were not run in CI (and had even to be fixed, see #45721).

### Describe how you validated your changes
1. `//internal/tools/modparser:modparser_test` plugged into existing `bazel:tests:linux-*` CI jobs,
2. linting through new `bazel:run-gazelle` and `bazel:run-go-mod-tidy` CI jobs,
3. local execution of `release.update-modules`:
```sh
# setup
dda inv worktree.init --branch regis.desgroppes/migrate-modparser-as-1st-go-module-to-bazel
# top-most wrapper-of-wrappers command eventually invoking `bazel run //internal/tools/modparser`
dda inv release.update-modules --version 7.77.0
```
... resulting in:
```diff
diff --git a/comp/core/agenttelemetry/def/go.mod b/comp/core/agenttelemetry/def/go.mod
index 7518813a09..64d1f43b70 100644
--- a/comp/core/agenttelemetry/def/go.mod
+++ b/comp/core/agenttelemetry/def/go.mod
@@ -2,13 +2,13 @@ module github.com/DataDog/datadog-agent/comp/core/agenttelemetry/def
 
 go 1.24.0
 
-require github.com/DataDog/datadog-agent/pkg/fleet/installer v0.70.0
+require github.com/DataDog/datadog-agent/pkg/fleet/installer v0.77.0
 
 require (
-       github.com/DataDog/datadog-agent/pkg/template v0.73.2 // indirect
-       github.com/DataDog/datadog-agent/pkg/util/log v0.73.2 // indirect
-       github.com/DataDog/datadog-agent/pkg/util/scrubber v0.73.2 // indirect
-       github.com/DataDog/datadog-agent/pkg/version v0.73.2 // indirect
+       github.com/DataDog/datadog-agent/pkg/template v0.77.0 // indirect
+       github.com/DataDog/datadog-agent/pkg/util/log v0.77.0 // indirect
+       github.com/DataDog/datadog-agent/pkg/util/scrubber v0.77.0 // indirect
+       github.com/DataDog/datadog-agent/pkg/version v0.77.0 // indirect
        github.com/ebitengine/purego v0.9.1 // indirect
        github.com/go-ole/go-ole v1.3.0 // indirect
        github.com/lufia/plan9stats v0.0.0-20251013123823-9fd1530e3ec3 // indirect
diff --git a/comp/core/agenttelemetry/fx/go.mod b/comp/core/agenttelemetry/fx/go.mod
[...]
```

### Additional Notes
`.adms/bazel/adms.mirror.cfg`: new `rewrite` rule to download the Go SDK [due to](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1409573778#L3010):
```
ERROR: no such package '@@rules_go++go_sdk+main___download_0//': java.io.IOException: Cache miss and no url specified - Configured URL rewriter blocked all URLs: [https://dl.google.com/go/go1.25.6.linux-amd64.tar.gz] - This blocking should only be happening in CI - reach out to Datadog#dependency-management
```

`.gitlab/build/bazel/lint.yml`: Go linting jobs to make sure we remain in-sync.

`.gitlab/build/bazel/tests.yml`: extend the scope of `bazel test` (only on Linux only for the time being) to catch `modparser` tests as well as any newly migrated Go module. Unsurprisingly, failing targets had to be excluded due to the earlier lack of CI coverage.

`deps/go.MODULE.bazel`:
- the Go SDK version is **read** from the root `go.work` file,
- `gazelle`'s scope is currently limited to `//internal/tools/modparser:go.mod`, because we need to adjust in-repo Go sync scripts to switch to `//:go.mod`, then to `//:go.work` when all Go modules are migrated,
- the list of Go repositories is **generated** by `bazel mod tidy`.

`internal/tools/modparser/BUILD.bazel`: **generated** by `bazel run //:gazelle`.

`tasks/libs/common/gomodules.py`: now runs `modparser` through `bazel run`.

`BUILD.bazel`:
- plugs `gazelle` into the build (`bazel run //:gazelle`), with a TODO list of excluded directories containing `go.mod` files. Removing a `# gazelle:exclude some/path` line will later lead `bazel run //:gazelle` to generate `BUILD.bazel` files for each `go.mod` file under `some/path`,
- plugs `go` into the build: `bazel run //:go mod tidy`, etc.

`MODULE.bazel`: adds `gazelle` dependency and includes `deps/go.MODULE.bazel`.

`MODULE.bazel.lock`: one can see Go SDK 1.25.7 was selected, matching the version in `go.work`.

### Prerequisites
- #46211, abandoned in favor of:
- bazel-contrib/rules_go#4555 (contributed, merged and already in use in the repo).

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>