bump bazel windows container disk size (#53459)
### What does this PR do?
Adds `--storage-opt "size=100GB"` arg to the shared bazel windows docker container invocation

### Motivation
resolve flakes/failures from lack of disk space in `bazel:test:windows-amd64` jobs which are missing the `--storage-opt` flag (https://github.com/DataDog/datadog-agent/pull/53433)
```
ERROR: Error while writing profile file: C:\bob\command-db340673-8984-4b35-908d-5685bbf8d197.profile.gz -> C:\bob\command.profile.gz: There is not enough space on the disk
```
matches the regular test job container configuration
https://github.com/DataDog/datadog-agent/blob/b8231acf508cd0c19534f8f1f7d8866734c53e15/.gitlab/windows/build/source_test/windows.yml#L23



Co-authored-by: branden.clark <branden.clark@datadoghq.com>