Reduce lengthy output when running test with error (#40692)
### What does this PR do?

Running test with compiling error produce a tedious output to read. This
PR improve the user experience by reducing repeated information.

Examnple, before:
```
DONE 0 tests, 1 failure, 3 errors in 0.000s
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"# github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"comp/core/secrets/impl/secrets_test.go:344:26: cannot use \"\" (untyped string constant) as handleToContext value in struct literal\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"comp/core/secrets/impl/secrets_test.go:486:20: not enough arguments in call to assert.Equal\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"\thave (*testing.T, string)\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"\twant (assert.TestingT, interface{}, interface{}, ...interface{})\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-output","Output":"comp/core/secrets/impl/secrets_test.go:642:28: cannot use 123 (untyped int constant) as string value in array or slice literal\n"}
WARNING: Invalid line in result json file, skipping: {"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-fail"}
Tests failed (base flavor)
Test failures:
- github.com/DataDog/datadog-agent/comp/core/secrets/impl package failed due to panic / race condition
```

after:
```
DONE 0 tests, 1 failure, 3 errors in 0.000s
WARNING: Invalid line in result json file, skipping
# github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]
comp/core/secrets/impl/secrets_test.go:344:26: cannot use "" (untyped string constant) as handleToContext value in struct literal
comp/core/secrets/impl/secrets_test.go:486:20: not enough arguments in call to assert.Equal
have (*testing.T, string)
want (assert.TestingT, interface{}, interface{}, ...interface{})
comp/core/secrets/impl/secrets_test.go:642:28: cannot use 123 (untyped int constant) as string value in array or slice literal
{"ImportPath":"github.com/DataDog/datadog-agent/comp/core/secrets/impl [github.com/DataDog/datadog-agent/comp/core/secrets/impl.test]","Action":"build-fail"}
Tests failed (base flavor)
Test failures:
- github.com/DataDog/datadog-agent/comp/core/secrets/impl package failed due to panic / race condition
```

### Describe how you validated your changes

Running the CI is enough.