Bump `protobuf` Bazel dep to 34.1. (#48228)
### What does this PR do?
Following #46948, this is to update the `protobuf` Bazel module dependency from 29.1 to 34.1.

### Motivation
Several transitive dependencies now require `protobuf` >= 34.0, causing `Renovate` to [fail updating](https://github.com/DataDog/datadog-agent/pull/48223#issuecomment-4111584502) `MODULE.bazel.lock`:
> ERROR: For repository 'protobuf', the root module requires module version protobuf@29.1, but got protobuf@34.0.bcr.1 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off

Bumping to 34.1 satisfies that constraint and also aligns with the recent:
- #46948.

### Describe how you validated your changes
Built `@protobuf//:protobuf` locally.

### Additional Notes
- the existing patch (add `-lstdc++` to `//conditions:default` link opts) applies cleanly to 34.1 without modification,
- `34.0` wouldn't be enough, since it's **strictly less than** `34.0.bcr.1`.

Co-authored-by: regis.desgroppes <regis.desgroppes@datadoghq.com>